(* ::Package:: *)

(* ::Input:: *)
(*BeginPackage["Turtle`"]*)
(**)
(*update[] := Do[*)
(*state = {position, direction};*)
(*states = Append[states, state];*)
(*,1]*)
(**)
(*reset[] := Do[*)
(*states = {};*)
(*position = {0,0};*)
(*direction =0; *)
(*update[];*)
(*,1]*)
(**)
(*turn[deg_]:=Do[*)
(*direction = direction + deg;*)
(*update[];*)
(*,1]*)
(**)
(*pos[state_] := Part[state,1]*)
(**)
(**)
(*forward[steps_] := CompoundExpression[*)
(*x = position[[1]] + Sin[direction Degree] * steps;*)
(*y = position[[2]] + Cos[direction Degree] * steps;*)
(*position = {x, y};*)
(*update[];*)
(*]*)
(**)
(*points[] := Map[pos, states]*)
(*draw[] := Graphics[Line[points[]]]*)
(*EndPackage[]*)
